# Generated by Django 3.2.6 on 2021-08-12 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0004_auto_20210812_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedules', to='handbook.group')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_schedules', to='handbook.object')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
