# Generated by Django 3.2.6 on 2021-08-16 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mon', models.BooleanField(default=False)),
                ('monStart', models.CharField(default='00:00', max_length=5)),
                ('monEnd', models.CharField(default='23:59', max_length=5)),
                ('tue', models.BooleanField(default=False)),
                ('tueStart', models.CharField(default='00:00', max_length=5)),
                ('tueEnd', models.CharField(default='23:59', max_length=5)),
                ('wen', models.BooleanField(default=False)),
                ('wenStart', models.CharField(default='00:00', max_length=5)),
                ('wenEnd', models.CharField(default='23:59', max_length=5)),
                ('thu', models.BooleanField(default=False)),
                ('thuStart', models.CharField(default='00:00', max_length=5)),
                ('thuEnd', models.CharField(default='23:59', max_length=5)),
                ('fri', models.BooleanField(default=False)),
                ('friStart', models.CharField(default='00:00', max_length=5)),
                ('friEnd', models.CharField(default='23:59', max_length=5)),
                ('sun', models.BooleanField(default=False)),
                ('sunStart', models.CharField(default='00:00', max_length=5)),
                ('sunEnd', models.CharField(default='23:59', max_length=5)),
                ('sat', models.BooleanField(default=False)),
                ('satStart', models.CharField(default='00:00', max_length=5)),
                ('satEnd', models.CharField(default='23:59', max_length=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
