# Generated by Django 3.2.6 on 2021-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_businesshour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshour',
            old_name='friEnd',
            new_name='fri_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='friStart',
            new_name='fri_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='monEnd',
            new_name='mon_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='monStart',
            new_name='mon_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='satEnd',
            new_name='sat_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='satStart',
            new_name='sat_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='sunEnd',
            new_name='sun_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='sunStart',
            new_name='sun_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='thuEnd',
            new_name='thu_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='thuStart',
            new_name='thu_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='tueEnd',
            new_name='tue_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='tueStart',
            new_name='tue_start',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='wenEnd',
            new_name='wen_end',
        ),
        migrations.RenameField(
            model_name='businesshour',
            old_name='wenStart',
            new_name='wen_start',
        ),
    ]
