# Generated by Django 3.2.6 on 2021-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_finish_schedule_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
