# Generated by Django 3.2.6 on 2021-08-12 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('read', 'read'), ('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('login', 'login'), ('read_one', 'read_one')], max_length=10, null=True)),
                ('data', models.CharField(choices=[('account', 'account'), ('booking', 'booking'), ('handbook_group', 'handbook_group'), ('handbook_object', 'handbook_object'), ('log', 'log')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
