# Generated by Django 3.2.6 on 2021-08-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.CharField(choices=[('account', 'account'), ('booking', 'booking'), ('handbook_group', 'handbook_group'), ('handbook_object', 'handbook_object'), ('log', 'log')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('read', 'read'), ('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('login', 'login'), ('read_one', 'read_one'), ('reset_password', 'reset_password')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
