# Generated by Django 3.2.6 on 2021-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_log_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.CharField(choices=[('account', 'account'), ('booking', 'booking'), ('handbook_group', 'handbook_group'), ('handbook_object', 'handbook_object'), ('log', 'log'), ('booking_business_hour', 'booking_business_hour'), ('analytic', 'analytic')], max_length=30),
        ),
    ]
